[package]
name = "sip-honeypot"
version = "0.1.1"
authors = ["2026, Philippe TEMESI"]
description = "A SIP honeypot for detecting and analyzing SIP attacks"
repository = "https://www.tems.be"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
structopt = "0.3"
chrono = "0.4"
lazy_static = "1.4"
anyhow = "1.0"
regex = "1.9"

[target.'cfg(unix)'.dependencies]
daemonize = "0.5.0"
libc = "0.2"
